# Generated by Django 4.1.4 on 2023-02-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='name', help_text='add the client name ', max_length=100)),
                ('Mobile', models.CharField(default='Mobile', help_text='add the client Mobile ', max_length=225)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(default='Country', help_text='add the Country  ', max_length=100)),
                ('City', models.CharField(default='City', help_text='add the City ', max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Contract_Start_Date', models.DateField()),
                ('Contract_End_Date', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('not Active', 'not Active')], max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['-pk'],
            },
        ),
    ]
