# Generated by Django 4.1.4 on 2023-02-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='City',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Country',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='Mobile',
            field=models.CharField(default='Mobile', max_length=225),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
